FROM nginx:1.31.5-alpine@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

COPY ./conf/nginx-site.conf /etc/nginx/conf.d/default.conf
